# Generated by Django 4.0.3 on 2022-03-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyalty_code', models.CharField(default=0, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='carwash',
            name='carwash_purchased',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='carwash',
            name='free_code',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
    ]
