# Generated by Django 4.0.3 on 2022-03-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0002_loyaltycode_alter_carwash_carwash_purchased_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwash',
            name='used_codes',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
    ]
