# Generated by Django 4.1.2 on 2022-10-21 08:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0009_alter_carwash_used_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwash',
            name='used_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, null=True, size=None),
        ),
    ]
